(* * * * * * * * * * *
 * Resource Aware ML *
 * * * * * * * * * * *
 *
 * * *  Unit Tests * *
 *
 * File:
 *   tests/array.ml
 *
 * Author:
 *   Jan Hoffmann, Shu-Chun Weng (2014)
 * 
 * Description:
 *   Arrays.
 *   
 *)

let one = Rnat.succ Rnat.zero
let two = Rnat.succ one
let arr = Rarray.make two 1
let _ = Rarray.set arr Rnat.zero 3 ;;
Rarray.length arr,
Rarray.get arr Rnat.zero,
Rarray.get arr one
